apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-with-sdi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      # Python application container
      - name: python-app
        image: python-app:test
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: SDI_ENDPOINT
          value: "http://localhost:8080"
        - name: FLASK_ENV
          value: "development"
      
      # SDI sidecar container
      - name: sdi-sidecar
        image: sdi-sidecar:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: management
        env:
        - name: SDI_DETECTION_ENABLED
          value: "false"
        - name: SDI_KUBERNETES_ENABLED
          value: "false"
        - name: SDI_KAFKA_ENABLED
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
  - name: app
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: sdi
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort

